export const FIND_ALL_POSTS_REQUEST = "FIND_ALL_POSTS_REQUEST";
export const FIND_ALL_POSTS_SUCCESS = "FIND_ALL_POSTS_SUCCESS";
export const FIND_ALL_POSTS_FAIL = "FIND_ALL_POSTS_FAIL";

export const APPROVE_POST_REQUEST = " APPROVE_POST_REQUEST";
export const APPROVE_POST_SUCCESS = " APPROVE_POST_SUCCESS";
export const APPROVE_POST_FAIL = " APPROVE_POST_FAIL";